[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/email-capture"
  to = "/.netlify/functions/email-capture"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200