/**
 * Generator-Validator Integration Tests
 *
 * Tests the critical integration between generator and validator:
 * - Ensures generated files validate correctly with high scores
 * - Verifies official llmstxt.org format alignment
 * - Tests that generator output matches validator expectations
 * - Confirms generated files score 85-95/100 as required
 */

import { describe, it, expect, vi } from 'vitest';
import { validateLlmsTxt } from '../validation';

// Import the generator function (we'll need to test it indirectly via generated content)
// Since generateLlmTxtContent is in routes.ts and not exported, we'll test with
// realistic generated content samples

describe('Generator-Validator Integration', () => {

  it('should validate generated llms.txt with high score (85-95)', async () => {
    // Simulate generated content in spec-compliant llmstxt.org format
    // (metadata as plain text before H2 sections, Optional section with proper links)
    const generatedContent = `# example.com

> A comprehensive example site demonstrating best practices for llms.txt files

Generated by [LLM.txt Mastery](https://llmtxtmastery.com) on ${new Date().toISOString().split('T')[0]}. 6 pages found, 6 analyzed, 6 included. Average quality: 9.5/10.

## Documentation

- [Getting Started Guide](https://example.com/docs/getting-started): Quick introduction to using our platform
- [API Reference](https://example.com/docs/api): Complete API documentation with examples
- [Tutorial Series](https://example.com/docs/tutorials): Step-by-step guides for common tasks

## Resources

- [Blog](https://example.com/blog): Latest updates and technical articles
- [FAQ](https://example.com/faq): Frequently asked questions
- [Community Forum](https://example.com/forum): Ask questions and share knowledge

## Optional

- [Review Full Analysis](https://llmtxtmastery.com/analysis/view): View quality scores and make changes to this file
- [llms.txt Specification](https://llmstxt.org/): Official llmstxt.org format specification
`;

    // Create a mock server to serve this content
    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(generatedContent),
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://example.com');

    global.fetch = originalFetch;

    // Critical assertions: Generated files should score 85-95
    expect(result.valid).toBe(true);
    expect(result.score).toBeGreaterThanOrEqual(85);
    expect(result.score).toBeLessThanOrEqual(100);

    // Should have no errors
    const errors = result.issues.filter(i => i.severity === 'error');
    expect(errors.length).toBe(0);

    // Should have minimal warnings
    const warnings = result.issues.filter(i => i.severity === 'warning');
    expect(warnings.length).toBeLessThanOrEqual(1);
  });

  it('should detect all required elements in generated format', async () => {
    const generatedContent = `# Test Site

> This is a test description for validation

## Main Content

- [Page 1](https://test.com/page1): First page
- [Page 2](https://test.com/page2): Second page
- [Page 3](https://test.com/page3): Third page
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(generatedContent),
        } as Response);
      }
      // Mock HEAD requests for URL validation
      if (url.includes('/page')) {
        return Promise.resolve({
          ok: true,
          status: 200,
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://test.com');

    global.fetch = originalFetch;

    // Should detect H1 header (required)
    expect(result.issues.find(i => i.message.includes('H1 header'))).toBeUndefined();

    // Should detect blockquote (recommended)
    expect(result.issues.find(i => i.message.includes('blockquote'))).toBeUndefined();

    // Should find URLs (the validator extracts URLs from markdown links)
    const noUrlsWarning = result.issues.find(i => i.message.includes('No URLs found'));
    expect(noUrlsWarning).toBeUndefined();
  });

  it('should give bonus points for well-organized content', async () => {
    const wellOrganizedContent = `# Example Corp

> A comprehensive platform providing tools and services for developers to build better applications

## Documentation

- [Getting Started](https://example.com/start): Quick start guide
- [API Reference](https://example.com/api): Complete API documentation
- [Tutorials](https://example.com/tutorials): Step-by-step guides

## Tools

- [CLI Tool](https://example.com/cli): Command-line interface
- [SDKs](https://example.com/sdks): Client libraries
- [Playground](https://example.com/playground): Interactive testing

## Community

- [Forum](https://example.com/forum): Ask questions
- [Blog](https://example.com/blog): Latest updates
- [GitHub](https://github.com/example): Open source projects

## Support

- [Help Center](https://example.com/help): Support documentation
- [Contact](https://example.com/contact): Get in touch
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(wellOrganizedContent),
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://example.com');

    global.fetch = originalFetch;

    // Well-organized content should score very high
    expect(result.score).toBeGreaterThanOrEqual(90);

    // Should have:
    // - H1 header ✓
    // - Blockquote description >50 chars ✓ (+5 bonus)
    // - 10+ URLs ✓ (+5 bonus)
    // - Multiple H2 sections ✓ (+5 bonus)
    // Total base: 100 - minimal deductions + bonuses = 90-100
  });

  it('should penalize minimal format correctly', async () => {
    const minimalContent = `# Minimal Site

> Short description
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(minimalContent),
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://minimal.com');

    global.fetch = originalFetch;

    // Sprint 16: After Sprint 13/15 validator tightening, a minimal file with
    // no URLs is now considered invalid (structural requirement). Updated to
    // assert the new contract: invalid + below-perfect score + warning issue.
    expect(result.valid).toBe(false);
    expect(result.score).toBeLessThanOrEqual(75);

    // Should still surface a warning/error about missing URLs
    const noUrlsIssue = result.issues.find(i =>
      i.message.toLowerCase().includes('url') || i.message.toLowerCase().includes('link')
    );
    expect(noUrlsIssue).toBeDefined();
  });

  it('should validate generated content with semantic tags preserved in descriptions', async () => {
    const contentWithSemanticTags = `# TechDocs Platform

> Technical documentation platform for modern development teams

## API Documentation

- [REST API](https://techdocs.com/api/rest): Complete REST API reference with authentication and endpoints 🔑💻
- [GraphQL API](https://techdocs.com/api/graphql): GraphQL schema and query examples 🚀
- [Webhooks](https://techdocs.com/api/webhooks): Event-driven integration guide 🔔

## Guides

- [Getting Started](https://techdocs.com/guides/start): Quick introduction for new users 📚
- [Best Practices](https://techdocs.com/guides/best-practices): Recommended patterns and approaches ⭐
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(contentWithSemanticTags),
        } as Response);
      }
      // Mock HEAD requests for URL validation
      if (url.includes('/api/') || url.includes('/guides/')) {
        return Promise.resolve({
          ok: true,
          status: 200,
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://techdocs.com');

    global.fetch = originalFetch;

    // Should validate successfully with semantic tags in descriptions
    expect(result.valid).toBe(true);
    expect(result.score).toBeGreaterThanOrEqual(85);

    // URLs should be extracted correctly despite emoji/tags
    const noUrlsWarning = result.issues.find(i => i.message.includes('No URLs found'));
    expect(noUrlsWarning).toBeUndefined();
  });

  it('should recommend improvements for generated content that could be better', async () => {
    const goodButImprovableContent = `# Good Site

> Decent description

## Content

- [Page 1](https://good.com/page1): First page
- [Page 2](https://good.com/page2): Second page
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(goodButImprovableContent),
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://good.com');

    global.fetch = originalFetch;

    // Should be valid but have recommendations
    expect(result.valid).toBe(true);
    expect(result.recommendations.length).toBeGreaterThan(0);

    // Sprint 16: Recommendation titles changed in Sprint 13/15. Match more
    // flexibly — any URL-related recommendation is acceptable.
    const moreUrlsRec = result.recommendations.find(r =>
      r.title.toLowerCase().includes('url') || r.title.toLowerCase().includes('link')
    );
    expect(moreUrlsRec).toBeDefined();
  });

  it('should detect spec violations in non-compliant metadata sections', async () => {
    // Old-format content with H3 headings and plain text inside H2 sections
    const contentWithBadMetadata = `# Example Site

> Comprehensive documentation platform

## Documentation

- [Getting Started](https://example.com/start): Quick start guide
- [API Reference](https://example.com/api): Complete API documentation
- [Guides](https://example.com/guides): Detailed tutorials

## Generated Metadata

Generated by LLM.txt Mastery on 2025-01-15

### Analysis Summary

Total URLs: 3
Quality Score: 95/100
Content Depth: Comprehensive

### Additional Resources

- [View Analysis](https://llmtxt.com/analysis/abc123)
- [About llms.txt](https://llmstxt.org/)
`;

    const originalFetch = global.fetch;
    global.fetch = vi.fn((url: string) => {
      if (url.includes('/llms.txt')) {
        return Promise.resolve({
          ok: true,
          status: 200,
          text: () => Promise.resolve(contentWithBadMetadata),
        } as Response);
      }
      return originalFetch(url);
    });

    const result = await validateLlmsTxt('https://example.com');

    global.fetch = originalFetch;

    // Should still be valid (no errors, only warnings) but score lower
    expect(result.valid).toBe(true);

    // Should detect spec violations (H3 headings, plain text in H2 sections)
    const specWarnings = result.issues.filter(i =>
      i.message.includes('Plain text content is not allowed') ||
      i.message.includes('H3+ heading not allowed') ||
      i.message.includes('Malformed list item')
    );
    expect(specWarnings.length).toBeGreaterThan(0);

    // Score should be penalized for spec violations
    expect(result.score).toBeLessThan(100);
  });
});
